//go:build ignore

// Command knownfiles generates known_files_gen.go from GitHub Linguist's languages.yml.
//
// It maps Linguist language names to config-file-validator file types and extracts
// the "filenames" entries for each supported type.
//
// Usage:
//
//	go run ./internal/generate/knownfiles
package main

import (
	"context"
	"fmt"
	"io"
	"net/http"
	"os"
	"slices"
	"sort"
	"strings"
	"time"

	"gopkg.in/yaml.v3"
)

const (
	linguistURL = "https://raw.githubusercontent.com/github-linguist/linguist/refs/heads/main/lib/linguist/languages.yml"
	outputFile  = "known_files_gen.go"
	outputFile  = "pkg/filetype/known_files_gen.go"
)

// linguistLanguage represents the subset of fields we need from languages.yml.
type linguistLanguage struct {
	Filenames []string `yaml:"filenames"`
	Group     string   `yaml:"group"`
	TMScope   string   `yaml:"tm_scope"`
}

// languageToFileType maps Linguist language names to our file type names.
var languageToFileType = map[string]string{
	"JSON":               "json",
	"JSON with Comments": "jsonc",
	"YAML":               "yaml",
	"XML":                "xml",
	"TOML":               "toml",
	"INI":                "ini",
	"Java Properties":    "properties",
	"HCL":                "hcl",
	"CSV":                "csv",
}

// tmScopeToFileType maps TextMate scopes to file types as a fallback
// for languages that aren't directly named in languageToFileType but
// use a relevant grammar (e.g., Ant Build System uses text.xml.ant).
var tmScopeToFileType = map[string]string{
	"source.ini":    "ini",
	"source.dosini": "ini",
	"source.yaml":   "yaml",
	"text.xml":      "xml",
	"source.json":   "json",
	"source.toml":   "toml",
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	data, err := fetchLanguages()
	if err != nil {
		return fmt.Errorf("fetching languages.yml: %w", err)
	}

	var languages map[string]linguistLanguage
	if err := yaml.Unmarshal(data, &languages); err != nil {
		return fmt.Errorf("parsing languages.yml: %w", err)
	}

	knownFiles := extractKnownFiles(languages)
	return writeOutput(knownFiles)
}

func fetchLanguages() ([]byte, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	req, err := http.NewRequestWithContext(ctx, http.MethodGet, linguistURL, nil)
	if err != nil {
		return nil, err
	}

	resp, err := http.DefaultClient.Do(req)
	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Get(linguistURL)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("HTTP %d from %s", resp.StatusCode, linguistURL)
	}
	return io.ReadAll(resp.Body)
}

func resolveFileType(langName string, lang linguistLanguage) string {
	if ft, ok := languageToFileType[langName]; ok {
		return ft
	}
	if lang.Group != "" {
		if ft, ok := languageToFileType[lang.Group]; ok {
			return ft
		}
	}
	for prefix, ft := range tmScopeToFileType {
		if strings.HasPrefix(lang.TMScope, prefix) {
			return ft
		}
	}
	return ""
}

func extractKnownFiles(languages map[string]linguistLanguage) map[string][]string {
	result := make(map[string][]string)
	seen := make(map[string]map[string]bool)

	for langName, lang := range languages {
		if len(lang.Filenames) == 0 {
			continue
		}
		ft := resolveFileType(langName, lang)
		if ft == "" {
			continue
		}
		if seen[ft] == nil {
			seen[ft] = make(map[string]bool)
		}
		for _, f := range lang.Filenames {
			if !seen[ft][f] {
				seen[ft][f] = true
				result[ft] = append(result[ft], f)
			}
		}
	}

	for ft := range result {
		slices.Sort(result[ft])
		sort.Strings(result[ft])
	}
	return result
}

func writeOutput(knownFiles map[string][]string) error {
	var b strings.Builder

	b.WriteString("// Code generated by go generate; DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// Source: %s\n\n", linguistURL)
	b.WriteString(fmt.Sprintf("// Source: %s\n\n", linguistURL))
	b.WriteString("package filetype\n\n")
	b.WriteString("// LinguistKnownFiles maps file type names to known filenames\n")
	b.WriteString("// sourced from GitHub Linguist's languages.yml.\n")
	b.WriteString("var LinguistKnownFiles = map[string][]string{\n")

	fileTypes := make([]string, 0, len(knownFiles))
	for ft := range knownFiles {
		fileTypes = append(fileTypes, ft)
	}
	slices.Sort(fileTypes)

	for _, ft := range fileTypes {
		files := knownFiles[ft]
		fmt.Fprintf(&b, "\t%q: {\n", ft)
		for _, f := range files {
			fmt.Fprintf(&b, "\t\t%q,\n", f)
	sort.Strings(fileTypes)

	for _, ft := range fileTypes {
		files := knownFiles[ft]
		b.WriteString(fmt.Sprintf("\t%q: {\n", ft))
		for _, f := range files {
			b.WriteString(fmt.Sprintf("\t\t%q,\n", f))
		}
		b.WriteString("\t},\n")
	}

	b.WriteString("}\n")

	return os.WriteFile(outputFile, []byte(b.String()), 0600)
	return os.WriteFile(outputFile, []byte(b.String()), 0644)
}
