# MegaLinter GitHub Action configuration file
# More info at https://megalinter.io
---
name: MegaLinter

on: # yamllint disable-line rule:truthy - false positive
  push:

  pull_request:
    branches:
      - main
      - master

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions: # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  megalinter:
    name: MegaLinter
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      # Git Checkout
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}

      # MegaLinter
      - name: MegaLinter
        uses: oxsecurity/megalinter@8fbdead70d1409964ab3d5afa885e18ee85388bb # v9.4.0
        id: megalinter
        env:
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload MegaLinter artifacts
      - name: Archive production artifacts
        if: success() || failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: MegaLinter reports
          path: |
            megalinter-reports
            mega-linter.log
